apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webpython
  name: webpython
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpython
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webpython
    spec:
      containers:
      - image: kshamama/webpython:latest
        name: webpython
        resources: {}
status: {}
