apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webpython
  name: lb
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: webpython
  type: LoadBalancer
status:
  loadBalancer: {}
